### ISSUE TITLE
circular import issue

### ISSUE THREAD

**Issue by infosecurii** [cisagov/ScubaGoggles#372]
# 🐛 Summary #

ImportError: cannot import name 'Enum' from partially initialized module 'enum' (most likely due to a circular import) (C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\enum.py)

## To reproduce ##

in .venv  installed dependencies from requirements.txt, and executed the tool using the scuba.py script located in the root directory of the repository. Replaced any scubagoggles directions with python scuba.py

ran python scuba.py gws 

see error below

## Expected behavior ##

What did you expect to happen that didn't?

## Any helpful log output or screenshots ##

Paste the results here:

(.venv) C:\Scubagoggles\sgmodule>python scuba.py gws
Traceback (most recent call last):
  File "C:\Scubagoggles\sgmodule\scuba.py", line 14, in <module>
    from scubagoggles.main import dive # pylint: disable=import-error wrong-import-position
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Scubagoggles\sgmodule\scubagoggles\main.py", line 8, in <module>
    import argparse
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\argparse.py", line 89, in <module>
    import re as _re
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 124, in <module>
    import enum
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\enum.py", line 3, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "C:\Scubagoggles\sgmodule\./scubagoggles\types.py", line 6, in <module>
    from enum import Enum
ImportError: cannot import name 'Enum' from partially initialized module 'enum' (most likely due to a circular import) (C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\enum.py)

```
![image](https://github.com/user-attachments/assets/62d13760-afce-4ac5-9e31-0c3a49f30201)
![Enum error](https://github.com/user-attachments/assets/f2b94ec7-c074-4dcc-81bf-8112af15c9da)

**Comment by adhilto** [comment]
@rlxdev This issue should be fixed by https://github.com/cisagov/ScubaGoggles/pull/356 (literally merged into main just now). Might be a good idea to test ScubaGoggles on the latest from main on Python 3.11 to verify, but this should be fixed now.

**Comment by infosecurii** [comment]
@adhilto @rlxdev  Ran the tool yesterday with success. No longer receiving errors. Thank you!
